/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AffiliateAbi } from "./AffiliateAbi";
export * as factories from "./factories";
export { AffiliateAbi__factory } from "./factories/AffiliateAbi__factory";
