/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AffiliateAbi__factory } from "./AffiliateAbi__factory";
export { Erc20Abi__factory } from "./Erc20Abi__factory";
